//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
            this.FeedBacks = new HashSet<FeedBack>();
        }
        [RegularExpression(@"^[\s]*[a-zA-Z0-9]{4,15}$")]
        [Required(ErrorMessage = "User name must from 4 to 15 characters.Only character and number.")]
        public string CusName { get; set; }
        [Required(ErrorMessage ="Please enter your password")]
        [RegularExpression(@"^[\s]*[a-zA-Z0-9]{4,15}$", ErrorMessage = "Password must from 4 to 15 characters.Only character and number.")]
        //[RegularExpression(@"^(?=.*[A-Z].*[A-Z])(?=.*[!@#$&*])(?=.*[0-9].*[0-9])(?=.*[a-z].*[a-z].*[a-z]).{8}$", ErrorMessage = "Username and password do not enter special characters.")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Please enter your fullname.")]
        public string FullName { get; set; }       
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Birth date must be in the correct format dd/mm/yyyy. ")]
        public Nullable<System.DateTime> BirthDay { get; set; }
        [Required( ErrorMessage = "Please enter gender.")]
        public string Gender { get; set; }
        [RegularExpression(@"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z",ErrorMessage = "Please enter correct email address")]
        public string Email { get; set; }
        [RegularExpression(@"^[0-9]{10,11}$", ErrorMessage ="Phone must from 10 to 11 munber.")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Please enter your address.")]
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedBack> FeedBacks { get; set; }
    }
}
