//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FeedBack
    {
        public int FBackID { get; set; }
        [Required(ErrorMessage ="Please enter title.")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Please enter content.")]
        public string Content { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CusName { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
