//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ProID { get; set; }
        [Required(ErrorMessage ="Please enter name product.")]
        public string ProName { get; set; }
        [Required(ErrorMessage = "Please choose category.")]
        public Nullable<int> CateID { get; set; }
        [Required(ErrorMessage = "Please enter price.")]
        public Nullable<int> Price { get; set; }
        public Nullable<bool> Specials { get; set; }
        public string Description { get; set; }
        [Required(ErrorMessage = "Please choose origin product.")]
        public string Origin { get; set; }
        [Required(ErrorMessage = "Please choose image product.")]
        public string Image { get; set; }
        [Required(ErrorMessage ="Please choose brand")]
        public Nullable<int> BrandID { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
